Description: Setup an Amazon Linux Web server

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 keypair to enable SSH access to the instance

  SSHCIDR:
    Type: String
    Description: The CIDR block restricting SSH
    MinLength: 9
    Default: 131.247.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x

Mappings:
  Region2AMI:
    us-east-2:
      AMI: ami-0998bf58313ab53da
    us-west-1:
      AMI: ami-021bb9f371690f97a
    us-east-1:
      AMI: ami-0e2ff28bfb72a4e45
    us-west-2:
      AMI: ami-079f731edfe27c29c
    ap-south-1:
      AMI: ami-05695932c5299858a
    ap-northeast-2:
      AMI: ami-0ecd78c22823e02ef
    ap-southeast-1:
      AMI: ami-043afc2b8b6cfba5c
    ap-southeast-2:
      AMI: ami-01393ce9a3ca55d67
    ap-northeast-1:
      AMI: ami-02ddf94e5edc8e904
    ca-central-1:
      AMI: ami-0fa94ecf2fef3420b
    eu-central-1:
      AMI: ami-0ba441bdd9e494102
    eu-west-1:
      AMI: ami-0e61341fa75fcaa18
    eu-west-2:
      AMI: ami-050b8344d77081f4b
    eu-west-3:
      AMI: ami-053418e626d0549fc
    eu-north-1:
      AMI: ami-01a7a49829bda9d79
    me-south-1:
      AMI: ami-0f9dd846ebb1d7a81
    sa-east-1:
      AMI: ami-05b7dbc290217250d

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
              mysql-server: []

          files:
            /var/www/html/index.html:
              content: !
                <h1>Joshua D Cloud Formation Server</h1>
                <h2>including CF Scripts</h2>
                <p>Welcome to one and all</p>
              mode: '00644'
              owner: root
              group: root
              
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                interval=1
              mode: '000400'
              owner: root
              group: root
              
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.EC2Instance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}
                runas=root
              mode: '000400'
              owner: root
              group: root
              
          services:
            sysvinit:
              httpd:
                enabled: 'true'
                ensureRunning: 'true'
                
              cfn-hup:
                enabled: 'true'
                ensureRunnig: 'true'
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf
                  
              mysqld:
                enabled: 'true'
                ensureRunning: 'true'
      
    Properties:
      ImageId: !FindInMap [Region2AMI, !Ref 'AWS::Region', 'AMI']
      InstanceType: t2.micro
      SecurityGroups:
      - !Ref WebserverSecurityGroup
      Tags:
      - Key: Name
        Value: Amazon Linux Web Server
      KeyName: !Ref KeyName
      UserData:
        'Fn::Base64': !Sub |
          #!/bin/bash -x
          yum update -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}

  WebserverSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows HTTP
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        ToPort: 80
        IpProtocol: tcp
      - CidrIp: !Ref SSHCIDR
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp
        
Outputs:
  WebURL:
    Description: The URL for the web page.
    Value: !Sub 'http://${EC2Instance.PublicIp}'